name: Sync

on:
  push:
    branches:
      - main

jobs:
  bitbucket:
    name: Bitbucket
    uses: penske-media-corp/github-workflows-wordpress/.github/workflows/sync-bitbucket.yml@main
    with:
      repo_url: git@bitbucket.org:REPO_ORG/REPO_SLUG.git
      destination_branch: master
    secrets:
      SSH_KEY: ${{ secrets.BITBUCKET_SYNC_SSH_KEY }}
