name: PMC WordPress Workflows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    uses: penske-media-corp/github-workflows-wordpress/.github/workflows/build.yml@main
    secrets:
      BITBUCKET_READ_ONLY_SSH_KEY: ${{ secrets.BITBUCKET_READ_ONLY_SSH_KEY }}
      GITHUB_READ_ONLY_SSH_KEY: ${{ secrets.PMC_GITHUB_ACTION_SSH_KEY }}

  coding-standards:
    name: Coding Standards
    uses: penske-media-corp/github-workflows-wordpress/.github/workflows/coding-standards.yml@main
    secrets:
      BITBUCKET_READ_ONLY_SSH_KEY: ${{ secrets.BITBUCKET_READ_ONLY_SSH_KEY }}
      GITHUB_READ_ONLY_SSH_KEY: ${{ secrets.PMC_GITHUB_ACTION_SSH_KEY }}

  linting:
    name: Linting
    uses: penske-media-corp/github-workflows-wordpress/.github/workflows/linting.yml@main
    secrets:
      BITBUCKET_READ_ONLY_SSH_KEY: ${{ secrets.BITBUCKET_READ_ONLY_SSH_KEY }}
      GITHUB_READ_ONLY_SSH_KEY: ${{ secrets.PMC_GITHUB_ACTION_SSH_KEY }}

  pr-ai-summarizer:
    name: AI Pull Requests Summarizer
    uses: penske-media-corp/github-workflows-wordpress/.github/workflows/pmc-ai-pr-summarizer.yml@main
    secrets:
      SSH_KEY: ${{ secrets.PMCDEVOPS_SSH_PRIVATE_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}

  unit-tests:
    name: Unit Tests
    uses: penske-media-corp/github-workflows-wordpress/.github/workflows/unit-tests.yml@main
    secrets:
      BITBUCKET_READ_ONLY_SSH_KEY: ${{ secrets.BITBUCKET_READ_ONLY_SSH_KEY }}
      GITHUB_READ_ONLY_SSH_KEY: ${{ secrets.PMC_GITHUB_ACTION_SSH_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
