name: Build

on:
  workflow_call:
    secrets:
      BITBUCKET_READ_ONLY_SSH_KEY:
        required: true
      GITHUB_READ_ONLY_SSH_KEY:
        required: true

permissions:
  contents: read

jobs:
  assets:
    name: Assets
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Build static assets
        run: |
          cwd=$(pwd)

          # Find all the package.json files not in node_modules and store as an array
          packagejsons=()
          while IFS=  read -r -d $'\0'; do
            packagejsons+=("$REPLY")
          done < <(find . -maxdepth 3 -type d -name "*node_modules*" -prune -o -name "package.json" -print0)

          set -e
          for i in "${packagejsons[@]}"
          do
            pushd $( dirname $i )
            if [[ -f "package.json" ]]; then
              pwd

              if [[ ! -f ".nvmrc" ]]; then
                echo "WARNING: No .nvmrc found for $PWD"
                exit 1
              fi

              nvm install
              if [[ $( npm run | grep 'build' ) ]]; then
                npm config set unsafe-perm true
                npm config set user 0
                npm ci
                npm run build || { echo 'Build Failed'; exit 1; }
              fi
            fi
            popd
          done

          # Return to the original directory
          cd $cwd;

      - name: Ensure version-controlled files are not modified during the tests
        run: git diff --exit-code
