name: Build

on:
  workflow_call:
    secrets:
      BITBUCKET_READ_ONLY_SSH_KEY:
        required: true
      GITHUB_READ_ONLY_SSH_KEY:
        required: true

permissions:
  contents: read

jobs:
  assets:
    name: Assets
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: false

    concurrency:
      group: ${{ github.ref_name || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Build static assets
        run: |
          echo "Not implemented"
          exit 0
