name: Coding Standards

on:
  workflow_call:
    secrets:
      BITBUCKET_READ_ONLY_SSH_KEY:
        required: true
      GITHUB_READ_ONLY_SSH_KEY:
        required: true

permissions:
  contents: read

jobs:
  phpcs:
    name: PHP
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: ${{ github.repository != 'penske-media-corp/github-workflows-wordpress' }}

    steps:
      - name: Prepare environment
        uses: penske-media-corp/github-action-wordpress-test-setup@main
        with:
          bitbucket_read_only_ssh_key: "${{ secrets.BITBUCKET_READ_ONLY_SSH_KEY }}"
          git_checkout_fetch_depth: 0
          github_read_only_ssh_key: "${{ secrets.GITHUB_READ_ONLY_SSH_KEY }}"
          phpcs: 1

      # TODO: cache for a day?
      - name: Install PHPCS and PMC standards
        run: |
          git clone --depth 1 git@bitbucket.org:penskemediacorp/pmc-codesniffer.git "${RUNNER_TEMP}/phpcs"
          composer --working-dir="${RUNNER_TEMP}/phpcs" install
          echo "${RUNNER_TEMP}/phpcs/vendor/bin" >> $GITHUB_PATH

      - name: Log PHPCS debug information
        run: |
          phpcs -i
          phpcs --config-show

      - name: Set text domain
        if: ${{ github.repository != 'penske-media-corp/pmc-plugins' }}
        run: grep -Eoh 'PMC_TEXT_DOMAIN=([a-z\-]+)' "${GITHUB_WORKSPACE}/docker-compose.env" >> $GITHUB_ENV

      - name: Run PHPCS
        run: |
          . pmc-manifest
          . pmc-test-phpcs

      - name: Ensure version-controlled files are not modified during the tests
        run: git diff --exit-code

  # Runs the JavaScript coding standards checks.
  #
  # JSHint violations are not currently reported inline with annotations.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Logs debug information about the GitHub Action runner.
  # - Installs NodeJS.
  # - Logs updated debug information.
  # _ Installs NPM dependencies.
  # - Run the WordPress JSHint checks.
  # - Ensures version-controlled files are not modified or deleted.
#  jshint:
#    name: JavaScript coding standards
#    runs-on: ubuntu-latest
#    timeout-minutes: 20
#    if: ${{ github.repository == 'WordPress/wordpress-develop' || github.event_name == 'pull_request' }}
#    env:
#      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: ${{ true }}
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
#
#      - name: Log debug information
#        run: |
#          npm --version
#          node --version
#          git --version
#          svn --version
#
#      - name: Install NodeJS
#        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # v3.3.0
#        with:
#          node-version-file: '.nvmrc'
#          cache: npm
#
#      - name: Log debug information
#        run: |
#          npm --version
#          node --version
#
#      - name: Install Dependencies
#        run: npm ci
#
#      - name: Run JSHint
#        run: npm run grunt jshint
#
#      - name: Ensure version-controlled files are not modified or deleted
#        run: git diff --exit-code
