name: Jenkins

on:
  workflow_call:
    inputs:
      JENKINS_URL:
        default: ''
        description: 'Destination Jenkins URL.'
        required: true
        type: string
      JOB_NAME:
        default: ''
        description: 'Jenkins Job Name.'
        required: true
        type: string
      PARAMETERS:
        default: ''
        description: 'Query string attaching to Jenkins URL.'
        required: false
        type: string
    secrets:
      JENKINS_BUILD_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  jenkins:
    name: Jenkins
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Job By Token
        run: |
          curl -s -o /dev/null -D -  "${{ inputs.JENKINS_URL }}?job=${{ inputs.JOB_NAME }}&token=${{ secrets.JENKINS_BUILD_TOKEN }}&${{ inputs.PARAMETERS }}"
