name: Linting

on:
  workflow_call:
    secrets:
      BITBUCKET_READ_ONLY_SSH_KEY:
        required: true
      GITHUB_READ_ONLY_SSH_KEY:
        required: true

permissions:
  contents: read

jobs:
  php:
    name: "PHP: ${{ matrix.job_label }}"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: ${{ github.repository != 'penske-media-corp/github-workflows-wordpress' }}

    concurrency:
      group: ${{ github.ref_name || github.run_id }}-linting-php
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.2'
            continue_on_error: false
            job_label: 'current'

    steps:
      - name: Prepare environment
        uses: penske-media-corp/github-action-wordpress-test-setup@main
        with:
          bitbucket_read_only_ssh_key: "${{ secrets.BITBUCKET_READ_ONLY_SSH_KEY }}"
          git_checkout_fetch_depth: 0
          github_read_only_ssh_key: "${{ secrets.GITHUB_READ_ONLY_SSH_KEY }}"
          php_version: ${{ matrix.php }}
          phpcs: 1

      - name: Run PHP linting
        run: |
          . pmc-manifest
          . pmc-test-phplint

      - name: Ensure version-controlled files are not modified during the tests
        run: git diff --exit-code

  js:
    name: JS
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: ${{ github.repository != 'penske-media-corp/github-workflows-wordpress' }}

    concurrency:
      group: ${{ github.ref_name || github.run_id }}-linting-js
      cancel-in-progress: true

    steps:
      - name: Prepare environment
        uses: penske-media-corp/github-action-wordpress-test-setup@main
        with:
          bitbucket_read_only_ssh_key: "${{ secrets.BITBUCKET_READ_ONLY_SSH_KEY }}"
          github_read_only_ssh_key: "${{ secrets.GITHUB_READ_ONLY_SSH_KEY }}"
          nodejs: 1

      - name: Install eslint
        run: |
          . "$NVM_DIR/nvm.sh" --no-use

          nvm install

          npm i -g eslint
          npm i -g lint-diff

      - name: Run eslint
        run: |
          . "$NVM_DIR/nvm.sh" --no-use
          . pmc-manifest

          nvm use

          . pmc-test-eslint

      - name: Ensure version-controlled files are not modified during the tests
        run: git diff --exit-code

  enforce-ts:
    name: enforce-ts
    runs-on: ubuntu-latest
    steps:
      - name: Enforce TypeScript
        uses: penske-media-corp/github-workflows-wordpress/composites/enforce-pmc-scripts@enforce-ts
