name: Merge main to qa

on:
  workflow_call:
    inputs:
      WORKFLOW_DISPATCH_NAME:
        default: 'Jenkins'
        description: 'Workflow to trigger after sync.'
        required: false
        type: string

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  merge-main-to-qa:
    name: Merge
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
            git config --local user.name "Github Actions"
      - name: Merge main back to qa
        run: |
          git fetch

          # make sure qa is latest
          git checkout feature/qa-sync-test
          git pull

          # make sure main is latest
          git checkout feature/PMCS-5327-jenkins
          git pull

          # create a temporary sync-master2qa branch to resolve conflict
          git checkout -b sync-main2qa
          # merge qa into sync-main2qa auto resolve by taking master branch code
          git merge -s ours --no-edit --allow-unrelated-histories feature/qa-sync-test

          # merge temp branch sync-main2qa into qa
          git checkout feature/qa-sync-test
          git merge --no-edit --allow-unrelated-histories sync-main2qa

          # remove the temp branch we just created
          git branch -D sync-main2qa

          # push code back to qa
          git push origin feature/qa-sync-test

          # Deploy qa branch to pmcqa
          gh workflow run "${{ inputs.WORKFLOW_DISPATCH_NAME }}" -r "feature/qa-sync-test"


