name: QAT

on:
  workflow_call:
    inputs:
      QA_SITE_DOMAIN:
        default: ''
        description: 'QA Site Domain'
        required: false
        type: string
      THEME_NAME:
        default: ''
        description: 'WP Theme'
        required: false
        type: string

    secrets:
      CHECKLY_API_KEY:
        required: false
      CHECKLY_ACCOUNT_ID:
        required: false

jobs:
  qat:
    name: QAT
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: ${{ github.repository != 'penske-media-corp/github-workflows-wordpress' }}

    concurrency:
      group: ${{ github.ref_name || github.run_id }}-qat-check
      cancel-in-progress: true
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          # GITHUB_HEAD_REF will only be set during a PR
          if [[ "${GITHUB_HEAD_REF}" != "" ]]; then
            # This is a pull request
            BRANCH_NAME=${GITHUB_HEAD_REF#*/}
          else
            # This is the 'main' branch
            BRANCH_NAME=${GITHUB_REF##*/}
          fi

          # Set environment URLs based on the branch name
          #
          # The `version-hash` file is created by jenkins script when a branch is pushed
          # https://github.com/penske-media-corp/pmc-jenkins-scripts/blob/8ee0244a8485b61cfa6d3f9af00f7e6a55ddb042/bin/push-pmcqa-repo.sh#L36-L38
          # 
          # Examples
          #
          # Feature branch example:
          # ENVIRONMENT_URL: "https://test.sourcingjournal.pmcqa.com"
          # HASH_URL: "https://test.sourcingjournal.pmcqa.com/wp-content-vipgo-sites/test/themes/vip/pmc-sourcingjournal-2021/version-hash"
          #
          # main branch example:
          # ENVIRONMENT_URL: "https://sourcingjournal.pmcqa.com"
          # HASH_URL: "https://sourcingjournal.pmcqa.com/wp-content-vipgo/themes/vip/pmc-sourcingjournal-2021/version-hash"
          #
          if [[ "$BRANCH_NAME" == "main" ]]; then
            ENVIRONMENT_URL="https://${{ inputs.QA_SITE_DOMAIN }}"
            HASH_URL="https://${{ inputs.QA_SITE_DOMAIN }}/wp-content-vipgo/themes/vip/${{ inputs.THEME_NAME }}/version-hash"
          else
            ENVIRONMENT_URL="https://${BRANCH_NAME}.${{ inputs.QA_SITE_DOMAIN }}"
            HASH_URL="https://${BRANCH_NAME}.${{ inputs.QA_SITE_DOMAIN }}/wp-content-vipgo-sites/${BRANCH_NAME}/themes/vip/${{ inputs.THEME_NAME }}/version-hash"
          fi

          echo "ENVIRONMENT_URL=$ENVIRONMENT_URL" >> $GITHUB_ENV
          echo "HASH_URL=$HASH_URL" >> $GITHUB_ENV      

      - name: Quality Assurance Testing (QAT)
        id: qat
        uses: penske-media-corp/pmc-github-actions/actions/tests/checkly@feature/qat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
          CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
          ENVIRONMENT_URL: ${{ env.ENVIRONMENT_URL }}
          HASH_URL: ${{ env.HASH_URL }}  
