name: QAT

on:
  workflow_call:
    inputs:
      QA_SITE_DOMAIN:
        default: ''
        description: 'QA Site Domain'
        required: false
        type: string
      THEME_NAME:
        default: ''
        description: 'WP Theme'
        required: false
        type: string

    secrets:
      BITBUCKET_READ_ONLY_SSH_KEY:
        required: true
      GITHUB_READ_ONLY_SSH_KEY:
        required: true

permissions:
  contents: read

jobs:
  playwright:
    name: Playwright
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      FEATURE_BRANCH_NAME: $(echo "${{ github.head_ref || github.ref_name }}" | sed -e 's/feature\/\(.*\)/\1/' | tr '[:upper:]' '[:lower:]')
      NPM_QAT_SCRIPT: "qat"
    if: ${{ github.repository != 'penske-media-corp/github-workflows-wordpress' }}

    concurrency:
      group: ${{ github.ref_name || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Prepare environment
        uses: penske-media-corp/github-action-wordpress-test-setup@main
        with:
          bitbucket_read_only_ssh_key: "${{ secrets.BITBUCKET_READ_ONLY_SSH_KEY }}"
          github_read_only_ssh_key: "${{ secrets.GITHUB_READ_ONLY_SSH_KEY }}"
          nodejs: 1

      - name: Check QAT Script and Feature Branch
        run: |
          has_qat=`jq -r '.scripts|to_entries[]|select(.key=="${{ env.NPM_QAT_SCRIPT }}")|.key' package.json 2>/dev/null | head -n 1 | wc -l`
          if [ $has_qat -eq 1 ] && [[ "${{ github.head_ref || github.ref_name }}" =~ 'feature/' ]]; then
            echo "RUN_QAT=true" >> $GITHUB_ENV
          else
            echo "Not a feature branch or qat script not found. Skipping Playwright tests."
            echo "RUN_QAT=false" >> $GITHUB_ENV
          fi

      - name: Check PMCQA
        if: ${{ env.RUN_QAT == 'true' && inputs.THEME_NAME  != '' && inputs.QA_SITE_DOMAIN != '' }}
        timeout-minutes: 10
        run: |
          # `version-hash` is created by jenkins script when a branch is pushed
          # https://github.com/penske-media-corp/pmc-jenkins-scripts/blob/8ee0244a8485b61cfa6d3f9af00f7e6a55ddb042/bin/push-pmcqa-repo.sh#L36-L38
          hash_url="https://${{ env.FEATURE_BRANCH_NAME }}.${{ inputs.QA_SITE_DOMAIN }}/wp-content-vipgo-sites/${{ env.FEATURE_BRANCH_NAME }}/themes/vip/${{ inputs.THEME_NAME }}/version-hash"
          echo "HASH_URL: $hash_url"
          hash=`curl --insecure $hash_url`
          until [[ $hash == ${{ github.event.pull_request.head.sha }} ]]; do
              echo -n "Waiting for Jenkins Deployment ... \n"
              hash=`curl --insecure $hash_url`
              sleep 5
          done

      - name: Install Playwright
        if: ${{ env.RUN_QAT == 'true' }}
        run: |
          . "$NVM_DIR/nvm.sh"

          nvm install

          # Playwright needs to be added in package.json as dependency
          npm ci

      - name: Run Playwright tests
        if: ${{ env.RUN_QAT == 'true' }}
        run: |
          if [ "${{ inputs.QA_SITE_DOMAIN }}" != '' ]; then
            export ENVIRONMENT_URL="https://${{ env.FEATURE_BRANCH_NAME }}.${{ inputs.QA_SITE_DOMAIN }}"
          fi
          npm run ${{ env.NPM_QAT_SCRIPT }}
