name: QAT

on:
  workflow_call:
    inputs:
      QA_SITE_DOMAIN:
        default: ''
        description: 'QA Site Domain'
        required: false
        type: string
      THEME_NAME:
        default: ''
        description: 'WP Theme'
        required: false
        type: string

    secrets:
      BITBUCKET_READ_ONLY_SSH_KEY:
        required: false
      GITHUB_READ_ONLY_SSH_KEY:
        required: false
      CHECKLY_API_KEY:
        required: true
      CHECKLY_ACCOUNT_ID:
        required: true

permissions:
  contents: read

# Set the necessary credentials and export variables we can use to instrument our test run. Use the ENVIRONMENT_URL
# to run your checks against staging, preview or production.
# See https://www.checklyhq.com/docs/cli/command-line-reference/#npx-checkly-deploy and supporting documentation for
# more details on Checkly environment variables.
env:
  CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
  CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
  ENVIRONMENT_URL: ${{ inputs.QA_SITE_DOMAIN }}
  CHECKLY_TEST_ENVIRONMENT: ${{ inputs.QA_SITE_DOMAIN }}
  CHECKLY_REPO_BRANCH: ${{ github.head_ref }}
  CHECKLY_REPO_COMMIT_OWNER: ${{ github.actor }}
  CHECKLY_REPO_SHA: ${{ github.sha }}
jobs:
  checkly-deploy:
    name: Checkly Run and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: ${{ github.repository != 'penske-media-corp/github-workflows-wordpress' }}

    concurrency:
      group: ${{ github.ref_name || github.run_id }}-checkly-qat
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Check out the full git history
      - uses: actions/setup-node@v3
        with:
          node-version: 16 # Checkly CLI requires Node.js 16 or higher.
      - name: Restore or cache node_modules # Restore node_modules cache if available
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies # Install NPM dependencies if cache miss
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run checks # Run Checkly checks and record test session
        id: run-checks
        run: npx checkly test -e ENVIRONMENT_URL=${{ env.ENVIRONMENT_URL }} -e CHECKLY_REPO_SHA=${{ env.CHECKLY_REPO_SHA }} --reporter=github --record
      - name: Create summary # Export Checkly report to GitHub job summary
        if: always() # Always generate report even if tests fail
        id: create-summary
        run: cat checkly-github-report.md > $GITHUB_STEP_SUMMARY
      - name: Deploy checks # Deploy checks to Checkly for debugging
        if: always() # Deploy regardless of test result
        id: deploy-checks
        run: npx checkly deploy --force
