name: QAT

on:
  workflow_call:
    inputs:
      SITE_URL:
        default: ''
        description: 'Site URL'
        required: false
        type: string
      THEME_NAME:
        default: ''
        description: 'WP Theme'
        required: false
        type: string

    secrets:
      BITBUCKET_READ_ONLY_SSH_KEY:
        required: true
      GITHUB_READ_ONLY_SSH_KEY:
        required: true

env:
  FEATURE_BRANCH_NAME: $(echo ${{ github.head_ref || github.ref_name }} | sed -e 's/feature\/\(.*\)/\1/' | tr '[:upper:]' '[:lower:]')
  NPM_QAT_SCRIPT: "qat:debug"

permissions:
  contents: read

jobs:
  playwright:
    name: Playwright
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    if: ${{ github.repository != 'penske-media-corp/github-workflows-wordpress' }}

    steps:
      - name: Prepare environment
        uses: penske-media-corp/github-action-wordpress-test-setup@main
        with:
          bitbucket_read_only_ssh_key: "${{ secrets.BITBUCKET_READ_ONLY_SSH_KEY }}"
          github_read_only_ssh_key: "${{ secrets.GITHUB_READ_ONLY_SSH_KEY }}"
          nodejs: 1

      - name: Check QAT Script and Feature Branch
        run: |
          has_qat=`jq -r '.scripts|to_entries[]|select(.key=="${{ env.NPM_QAT_SCRIPT }}")|.key' package.json 2>/dev/null | head -n 1 | wc -l`
          if [ $has_qat -eq 1 ] && [ `echo "${{ env.FEATURE_BRANCH_NAME }}" | grep feature\/ | wc -l` -eq 1  ]; then
            echo "RUN_QAT=true" >> $GITHUB_ENV
          else
            echo "RUN_QAT=false" >> $GITHUB_ENV
          fi

      - name: Check PMCQA
        if: ${{ env.RUN_QAT == 'true' }}
        timeout-minutes: 10
        run: |
          if [ "${{ inputs.THEME_NAME }}" = '' ] || [ "${{ inputs.SITE_URL }}" = '' ]; then
            echo "THEME_NAME or SITE_URL is not set";
            exit 1;
          fi
          hash_url="https://${{ env.FEATURE_BRANCH_NAME }}.${{ inputs.SITE_URL }}/wp-content-vipgo-sites/${{ env.FEATURE_BRANCH_NAME }}/themes/vip/${{ inputs.THEME_NAME }}/version-hash"
          echo "HASH_URL: $hash_url"
          hash=`curl --insecure $hash_url`
          until [[ $hash == ${{ github.sha }} ]]; do
              echo -n "Waiting for Jenkins Deployment ... \n"
              hash=`curl --insecure $hash_url`
              sleep 5
          done

      - name: Install Playwright
        if: ${{ env.RUN_QAT == 'true' }}
        run: |
          . "$NVM_DIR/nvm.sh"

          nvm install
          nvm use

          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        if: ${{ env.RUN_QAT == 'true' }}
        run: |
          export ENVIRONMENT_URL="https://${{ env.FEATURE_BRANCH_NAME }}.${{ inputs.SITE_URL }}"
          npm run ${{ env.NPM_QAT_SCRIPT }}
