name: QAT

on:
  workflow_call:
    inputs:
      QA_SITE_DOMAIN:
        default: ''
        description: 'QA Site Domain'
        required: false
        type: string
      THEME_NAME:
        default: ''
        description: 'WP Theme'
        required: false
        type: string

    secrets:
      CHECKLY_API_KEY:
        required: false
      CHECKLY_ACCOUNT_ID:
        required: false
        
      # these two secrets are added just to support older
      # themes which have no QAT, but define an older
      # version of the QAT job, e.g.
      # https://github.com/penske-media-corp/pmc-soaps-2018/blob/c555da8b7174d5691bf0b66b8a35f0260dc5128a/.github/workflows/pmc.yaml#L67-L72
      # once those are removed the below secrets may also be removed.
      BITBUCKET_READ_ONLY_SSH_KEY:
        required: false
      GITHUB_READ_ONLY_SSH_KEY:
        required: false

jobs:
  qat:
    name: QAT
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: ${{ github.repository != 'penske-media-corp/github-workflows-wordpress' }}

    concurrency:
      group: ${{ github.ref_name || github.run_id }}-qat-check
      cancel-in-progress: true
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          # GITHUB_HEAD_REF will only be set during a PR
          if [[ "${GITHUB_HEAD_REF}" != "" ]]; then
            # This is a pull request
            BRANCH_NAME=${GITHUB_HEAD_REF#*/}
          else
            # This is the 'main' branch
            BRANCH_NAME=${GITHUB_REF##*/}
          fi

          # Set environment URLs based on the branch name
          #
          # @see https://penskemedia.atlassian.net/wiki/x/IICBW
          if [[ "$BRANCH_NAME" == "main" ]]; then
            ENVIRONMENT_URL="https://${{ inputs.QA_SITE_DOMAIN }}"
            HASH_URL="https://${{ inputs.QA_SITE_DOMAIN }}/wp-content-vipgo/themes/vip/${{ inputs.THEME_NAME }}/version-hash"
          else
            ENVIRONMENT_URL="https://${BRANCH_NAME}.${{ inputs.QA_SITE_DOMAIN }}"
            HASH_URL="https://${BRANCH_NAME}.${{ inputs.QA_SITE_DOMAIN }}/wp-content-vipgo-sites/${BRANCH_NAME}/themes/vip/${{ inputs.THEME_NAME }}/version-hash"
          fi

          # Convert URLs to lowercase and export to environment
          echo "ENVIRONMENT_URL=$(echo $ENVIRONMENT_URL | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "HASH_URL=$(echo $HASH_URL | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV      

      - name: Quality Assurance Testing (QAT)
        id: qat
        uses: penske-media-corp/pmc-github-actions/actions/tests/checkly@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
          CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
          ENVIRONMENT_URL: ${{ env.ENVIRONMENT_URL }}
          HASH_URL: ${{ env.HASH_URL }}  
