name: Sync with Bitbucket

on:
  workflow_call:
    inputs:
      repo_url:
        default: ''
        description: 'Destination repository URL.'
        required: true
        type: string
      destination_branch:
        default: ''
        description: 'Destination branch, if other than branch that triggered the workflow.'
        required: false
        type: string
    secrets:
      SSH_KEY:
        required: true

permissions:
  contents: read

jobs:
  push:
    name: Push to Bitbucket
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: false

    concurrency:
      group: ${{ github.ref_name || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Add SSH key
        run: |
          mkdir -p "${HOME}/.ssh"

          if [[ ! -f "${HOME}/.ssh/known_hosts" ]]; then
            touch "${HOME}/.ssh/known_hosts"
          fi
          ssh-keyscan bitbucket.org >> "${HOME}/.ssh/known_hosts"

          eval `ssh-agent`
          ssh-add - <<<"$(echo "${{ secrets.SSH_KEY }}")"
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=${SSH_AGENT_PID}" >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set outputs
        id: set-outputs
        run: |
          echo "::set-output name=source_branch::${{ github.ref_name }}"

          if [[ "" == "${{ inputs.destination_branch }}" ]]; then
            echo "::set-output name=destination_branch::${{ github.ref_name }}"
          else
            echo "::set-output name=destination_branch::${{ inputs.destination_branch }}"
          fi

      - name: Push to Bitbucket
        run: |
          git remote add bitbucket ${{ inputs.repo_url }}
          git push -f bitbucket ${{ steps.set-outputs.outputs.source_branch }}:${{ steps.set-outputs.outputs.destination_branch }}

  delete:
    name: Delete from Bitbucket
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: ${{ github.event_name == 'delete' && github.repository != 'penske-media-corp/github-workflows-wordpress' }}

    steps:
      - name: Add SSH key
        run: |
          mkdir -p "${HOME}/.ssh"

          if [[ ! -f "${HOME}/.ssh/known_hosts" ]]; then
            touch "${HOME}/.ssh/known_hosts"
          fi
          ssh-keyscan bitbucket.org >> "${HOME}/.ssh/known_hosts"

          eval `ssh-agent`
          ssh-add - <<<"$(echo "${{ secrets.SSH_KEY }}")"
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> $GITHUB_ENV
          echo "SSH_AGENT_PID=${SSH_AGENT_PID}" >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set outputs
        id: set-outputs
        run: |
          if [[ "" == "${{ inputs.destination_branch }}" ]]; then
            echo "::set-output name=destination_branch::${{ github.ref_name }}"
          else
            echo "::set-output name=destination_branch::${{ inputs.destination_branch }}"
          fi

      - name: Delete from Bitbucket
        run: |
          git remote add bitbucket ${{ inputs.repo_url }}
          git push -d bitbucket ${{ steps.set-outputs.outputs.destination_branch }}
