name: Unit Tests

on:
  workflow_call:
    secrets:
      BITBUCKET_READ_ONLY_SSH_KEY:
        required: true


# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: ${{ github.event_name == 'pull_request' }} && ${{ github.repository != 'penske-media-corp/github-workflows-wordpress' }}

    steps:
      - name: Prepare environment
        uses: ethitter/test-composite-action@main
        with:
          git_checkout_fetch_depth: 0
          phpunit: 1
          ssh_key_encoded: "${{ secrets.BITBUCKET_READ_ONLY_SSH_KEY }}"

      # TODO: install WP. We also need some extra containers.

      - name: Install PHPUnit
        run: |
          if [[ $(php -v) =~ "PHP 8." ]]; then
            composer global require "phpunit/phpunit=9.*"
          elif [[ $(php -v) =~ "PHP 7." ]]; then
            composer global require "phpunit/phpunit=6.1.*"
          fi
    
          composer global require yoast/phpunit-polyfills

      # TODO: we'll need a matrix of PHP versions for this one, and a flag for which versions can fail.
      # TODO: we'll also need a matrix for WP versions, and a flag for which versions can fail.
      - name: Run PHPUnit
        run: phpunit

      - name: Ensure version-controlled files are not modified during the tests
        run: git diff --exit-code
